### ISSUE TITLE
[feature request] Slowness when full

### ISSUE THREAD

**Issue by timelady-victorious** [FoundationGames/MealAPI#3]
I think fullness is not buffed enough (people say that saturation healing is OP).
For this reason, I think you should get a *tiny* bit of slowness for each fullness bar, starting at bar 2.

**Comment by FoundationGames** [comment]
I don't want to add disadvantages in gameplay, the purpose of the mod is to allow modders to make food items beneficial.
Balancing gameplay by making one benefit in one area of gameplay create a drawback in a completely different area of gameplay is a bit of a cheap way of balancing, in my own opinion.
